### ISSUE TITLE
Repeating Errors After Running 

### ISSUE THREAD

**Issue by mericgeren** [TrinhNC/ros_hand_gesture_recognition#1]
Hello,

First of all, thank you for developing this package.

When I try to launch hand_sign.launch, I get this repeating error:

```

[ERROR] [1700838892.714985]: bad callback: <bound method HandSignRecognition.callback of <__main__.HandSignRecognition object at 0x7fac304be0>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/mericgeren/catkin_ws/src/ros_hand_gesture_recognition/src/hand_sign_recognition.py", line 36, in callback
    cv_image = self.bridge.imgmsg_to_cv2(image_msg)
  File "/home/mericgeren/catkin_ws/src/vision_opencv/cv_bridge/python/cv_bridge/core.py", line 163, in imgmsg_to_cv2
    dtype, n_channels = self.encoding_to_dtype_with_channels(img_msg.encoding)
  File "/home/mericgeren/catkin_ws/src/vision_opencv/cv_bridge/python/cv_bridge/core.py", line 99, in encoding_to_dtype_with_channels
    return self.cvtype2_to_dtype_with_channels(self.encoding_to_cvtype2(encoding))
  File "/home/mericgeren/catkin_ws/src/vision_opencv/cv_bridge/python/cv_bridge/core.py", line 91, in encoding_to_cvtype2
    from cv_bridge.boost.cv_bridge_boost import getCvType
ModuleNotFoundError: No module named 'cv_bridge.boost.cv_bridge_boost'
```

Could you offer your advice and guidance please?

Kindest regards.

**Comment by mericgeren** [comment]
The source of the issue was the code running in Python 3 while ROS was installed with Python 2.7 . I haven't seen this error since compiling ROS with Python 3 from the source. But, now I got another issue for which I will open another issue here.

Kindest regards.

**Comment by TrinhNC** [comment]
If you install ROS Noetic on Ubuntu 20.04, the default Python Version for the whole system is Python 3. If you are using a previous version, it would be Python 2 by default. Cheers,

**Comment by mericgeren** [comment]
Thank you for your kind advice. I had to use ROS Melodic and Ubuntu 18.04 since, I am using something other which requires me to use these Ubuntu and ROS versions.
